name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "main"
    paths:
      - "**.go"
      - "cmd/**"
      - "internal/**"
      - "go.mod"
      - "go.sum"
      - ".dockerignore"
      - "Dockerfile"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version-file: "go.mod"
      - name: Check formatting
        run: |
          go fmt ./...
      - name: Run go vet
        run: go vet ./...
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version-file: "go.mod"

      - name: Run tests
        run: go test -v ./...

  functional-test-scenarios:
    name: Functional Test Scenarios
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        test-name:
          - part1-split
          - pass-through
          - r00-split
          - zip-file
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version-file: "go.mod"

      - name: Build binary
        run: |
          go build -o roar ./cmd/roar
          chmod +x roar

      - name: Install needed dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y fuse3 libfuse3-dev tree

      - name: Mount ${{ matrix.test-name }}
        run: |
          mkdir -p ${{ runner.temp }}/roar-mount/test
          ./roar tests/data/functional-tests/examples/${{ matrix.test-name }} ${{ runner.temp }}/roar-mount/test &

      - name: Verify test ${{ matrix.test-name }} matches expected output
        run: |
          cd "{{ runner.temp }}/roar-mount/test"
          tree . > ${{ runner.temp }}/roar-mount-test-output.txt
          cd ~
          diff tests/data/functional-tests/results/${{ matrix.test-name }}.txt ${{ runner.temp }}/roar-mount-test-output.txt
          
